export const ADD_BOOK = 'ADD_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_ALL_BOOK = 'DELETE_ALL_BOOK';

/* fetch */
export const FETCH_BOOKS_LOADING = 'FETCH_BOOKS_LOADING';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';
